name: DevSecOps pipeline

on:
  push:
    branches: ["main"]


jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo manually
        run: |
            git clone https://github.com/${{ github.repository }} .



      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      
      - name: Install Dependencies
        run: |
         pip install bandit requests


      - name: Run Bandit Scan
        run: |
          bandit -r .


      - name: Install Gitleaks via Go
        run: |
          sudo apt update
          sudo apt install -y golang
          go install github.com/zricethezav/gitleaks/v8@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          gitleaks version


      - name: Build Docker Image
        run: docker build -t security-automation .


      # 🔎 Container Scan (Trivy)
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
        image-ref: security-automation
        format: table
        exit-code: 1
        ignore-unfixed: true