name: DevSecOps pipeline

on:
  push:
    branches: ["main"]


jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo manually
        run: |
            git clone https://github.com/${{ github.repository }} .



      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      
      - name: Install Dependencies
        run: |
         pip install bandit requests


      - name: Run Bandit Scan
        run: |
          bandit -r .


      - name: Run Gitleaks (CLI)
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_x64.tar.gz -O gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          ./gitleaks detect --source . --exit-code 1


      - name: Build Docker Image
        run: docker build -t security-automation .


